export const defaultCourses = [
  {
    title: "Full Stack Development",
    slug: "full-stack-development",
    description:
      "Complete web development from frontend to backend. Build real-world projects with industry mentors.",
    overview:
      "A comprehensive program covering frontend, backend and deployment. Includes mentorship and real-world projects to build a production-ready portfolio.",
    duration: "6 Months",
    students: "1200+",
    rating: 4.9,
    level: "Beginner to Advanced",
    tags: ["React", "Node.js", "MongoDB", "Express"],
    badge: "Most Popular",
    badgeColor: "bg-brand-orange",
    color: "from-brand-blue to-brand-blue-dark",
    iconName: "Layers",
    fee: "Rs 45,000",
    syllabus: [
      "HTML, CSS, JavaScript, TypeScript",
      "React, State Management, Routing",
      "Node.js, Express, REST APIs",
      "Databases: MongoDB & SQL",
      "Authentication, Testing, Deployment",
    ],
    order: 1,
  },
  {
    title: "Frontend Development",
    slug: "frontend-development",
    description:
      "Master modern frontend technologies and create stunning, responsive user interfaces.",
    overview: "Focuses on building pixel-perfect UIs, accessibility and performance with modern tooling.",
    duration: "3 Months",
    students: "850+",
    rating: 4.8,
    level: "Beginner",
    tags: ["HTML", "CSS", "React", "Tailwind", "Figma"],
    badge: "Trending",
    badgeColor: "bg-brand-blue",
    color: "from-brand-orange to-brand-orange-dark",
    iconName: "Code2",
    fee: "Rs 25,000",
    syllabus: [
      "HTML & CSS fundamentals",
      "Responsive layouts",
      "React & Hooks",
      "Tailwind & UI patterns",
    ],
    order: 2,
  },
  {
    title: "Backend Development",
    slug: "backend-development",
    description:
      "Build powerful server-side applications, APIs and handle databases like a pro.",
    overview: "Deep dive into server-side concepts, APIs, authentication and scalable architectures.",
    duration: "3 Months",
    students: "620+",
    rating: 4.7,
    level: "Intermediate",
    tags: ["Node.js", "Express", "REST API", "JWT", "C#"],
    badge: "New",
    badgeColor: "bg-green-500",
    color: "from-brand-blue to-brand-orange",
    iconName: "Server",
    fee: "Rs 30,000",
    syllabus: [
      "Node.js & Express",
      "API design",
      "Authentication & Security",
      "Databases & ORMs",
    ],
    order: 3,
  },
  {
    title: "Database Management",
    slug: "database-management",
    description:
      "Learn SQL & NoSQL databases, query optimization and data modeling techniques.",
    overview: "Covers relational & non-relational databases, indexing, optimization and backup strategies.",
    duration: "2 Months",
    students: "430+",
    rating: 4.6,
    level: "Beginner",
    tags: ["MySQL", "MongoDB", "PostgreSQL", "Redis"],
    badge: null,
    badgeColor: "",
    color: "from-brand-blue-dark to-brand-blue",
    iconName: "Database",
    fee: "Rs 18,000",
    syllabus: [
      "SQL fundamentals",
      "NoSQL concepts",
      "Indexing & Performance",
      "Backup & Replication",
    ],
    order: 4,
  },
  {
    title: "Agentic AI",
    slug: "agentic-ai",
    description:
      "Build AI agents that plan, use tools, and automate real workflows.",
    overview:
      "Learn agent architectures, prompt design, tool integration, and safe deployment of AI systems.",
    duration: "3 Months",
    students: "220+",
    rating: 4.9,
    level: "Intermediate",
    tags: ["LLMs", "Agents", "Tools", "RAG"],
    badge: "Trending",
    badgeColor: "bg-brand-blue",
    color: "from-brand-blue to-brand-orange",
    iconName: "Bot",
    fee: "Rs 40,000",
    syllabus: [
      "Prompting & LLM basics",
      "Agent architectures & planning",
      "Tool use & function calling",
      "RAG & knowledge integration",
      "Evaluation, safety, deployment",
    ],
    order: 5,
  },
  {
    title: "DevOps & Cloud",
    slug: "devops-cloud",
    description:
      "Deploy and manage applications on cloud platforms with DevOps best practices.",
    overview: "Learn containerization, CI/CD pipelines and fundamentals of cloud providers for production deployments.",
    duration: "3 Months",
    students: "290+",
    rating: 4.7,
    level: "Advanced",
    tags: ["Docker", "AWS", "CI/CD", "Linux", "Terraform"],
    badge: null,
    badgeColor: "",
    color: "from-brand-blue to-brand-orange",
    iconName: "Globe",
    fee: "Rs 35,000",
    syllabus: ["Linux basics", "Docker & Containers", "CI/CD", "AWS fundamentals"],
    order: 6,
  },
];
