services:
  - type: web
    name: registration-form-api-dev
    rootDir: server
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm run dev
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: development
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: FRONTEND_URI
        fromService:
          type: web
          name: registration-form-frontend-dev
          property: host

  - type: web
    name: registration-form-api-prod
    rootDir: server
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: FRONTEND_URI
        fromService:
          type: web
          name: registration-form-frontend-prod
          property: host

  - type: web
    name: registration-form-frontend-dev
    rootDir: client
    runtime: static
    plan: free
    buildCommand: npm ci && npm run build:dev
    staticPublishPath: dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /admin/login
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: registration-form-api-dev
          property: host

  - type: web
    name: registration-form-frontend-prod
    rootDir: client
    runtime: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /admin/login
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: registration-form-api-prod
          property: host
